# Generated by Django 5.2.9 on 2025-12-07 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('rating', models.FloatField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('overall_sentiment', models.CharField(blank=True, max_length=20)),
                ('sentiment_confidence', models.FloatField(default=0)),
                ('positive_percentage', models.FloatField(default=0)),
                ('negative_percentage', models.FloatField(default=0)),
                ('neutral_percentage', models.FloatField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AspectAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect_name', models.CharField(max_length=100)),
                ('sentiment', models.CharField(max_length=20)),
                ('confidence', models.FloatField(default=0)),
                ('positive_count', models.IntegerField(default=0)),
                ('negative_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('sample_reviews', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspects', to='reviews.product')),
            ],
            options={
                'db_table': 'aspect_analysis',
                'ordering': ['-confidence'],
                'unique_together': {('product', 'aspect_name')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=50, unique=True)),
                ('author', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('text', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('verified_purchase', models.BooleanField(default=False)),
                ('sentiment', models.CharField(blank=True, max_length=20)),
                ('sentiment_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.product')),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-date', '-rating'],
                'indexes': [models.Index(fields=['product', 'rating'], name='reviews_product_09d7d6_idx'), models.Index(fields=['sentiment'], name='reviews_sentime_15acff_idx')],
            },
        ),
    ]
